/****************************************************************************

COPYRIGHT (C) $Date: Sept 24, 2015 $
$CompanyInfo: CONTINENTAL AUTOMOTIVE GMBH $
ALL RIGHTS RESERVED.

The reproduction, transmission or use of this document or its contents is
not permitted without express written authority.
Offenders will be liable for damages. All rights, including rights created
by patent grant or registration of a utility model or design, are reserved.
---------------------------------------------------------------------------

$ProjectName: FRDM KL26-Z PLATFORM $

$Log: io_pcs_cnf.h $

$Author: Flueran Gabriel $

 ****************************************************************************/

#ifndef IO_PCS_CNF_H
#define IO_PCS_CNF_H


/** Includes **/

#include "io_pcs.h"

/** end of Includes **/

/** Defines **/

	/* Macros */

#define ARRAY_SIZE(array) sizeof(array)/sizeof(&array[0])

	/* end of Macros */

/* DESCRIPTION: defines used for PCS Configuration field */
#define CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE		(uint32)(IO_PCS_DSE_LOW_MASK | IO_PCS_PFE_DISABLE_MASK | IO_PCS_SRE_FAST_MASK | IO_PCS_PE_DISABLED_MASK)
#define CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__PULL_DOWN	(uint32)(IO_PCS_DSE_LOW_MASK | IO_PCS_PFE_DISABLE_MASK | IO_PCS_SRE_FAST_MASK | IO_PCS_PE_PULL_DOWN_MASK)
#define CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__PULL_UP	(uint32)(IO_PCS_DSE_LOW_MASK | IO_PCS_PFE_DISABLE_MASK | IO_PCS_SRE_FAST_MASK | IO_PCS_PE_PULL_UP_MASK)
#define CNF_IO_PCS_LOW_DS__NO_PF__SLOW_SLEW__NO_PE		(uint32)(IO_PCS_DSE_LOW_MASK | IO_PCS_PFE_DISABLE_MASK | IO_PCS_SRE_SLOW_MASK | IO_PCS_PE_DISABLED_MASK)
#define CNF_IO_PCS_LOW_DS__NO_PF__SLOW_SLEW__PULL_DOWN	(uint32)(IO_PCS_DSE_LOW_MASK | IO_PCS_PFE_DISABLE_MASK | IO_PCS_SRE_SLOW_MASK | IO_PCS_PE_PULL_DOWN_MASK)
#define CNF_IO_PCS_LOW_DS__NO_PF__SLOW_SLEW__PULL_UP	(uint32)(IO_PCS_DSE_LOW_MASK | IO_PCS_PFE_DISABLE_MASK | IO_PCS_SRE_SLOW_MASK | IO_PCS_PE_PULL_UP_MASK)

#define CNF_IO_PCS_LOW_DS__PF__FAST_SLEW__NO_PE			(uint32)(IO_PCS_DSE_LOW_MASK | IO_PCS_PFE_ENABLE_MASK | IO_PCS_SRE_FAST_MASK | IO_PCS_PE_DISABLED_MASK)
#define CNF_IO_PCS_LOW_DS__PF__FAST_SLEW__PULL_DOWN		(uint32)(IO_PCS_DSE_LOW_MASK | IO_PCS_PFE_ENABLE_MASK | IO_PCS_SRE_FAST_MASK | IO_PCS_PE_PULL_DOWN_MASK)
#define CNF_IO_PCS_LOW_DS__PF__FAST_SLEW__PULL_UP		(uint32)(IO_PCS_DSE_LOW_MASK | IO_PCS_PFE_ENABLE_MASK | IO_PCS_SRE_FAST_MASK | IO_PCS_PE_PULL_UP_MASK)
#define CNF_IO_PCS_LOW_DS__PF__SLOW_SLEW__NO_PE			(uint32)(IO_PCS_DSE_LOW_MASK | IO_PCS_PFE_ENABLE_MASK | IO_PCS_SRE_SLOW_MASK | IO_PCS_PE_DISABLED_MASK)
#define CNF_IO_PCS_LOW_DS__PF__SLOW_SLEW__PULL_DOWN		(uint32)(IO_PCS_DSE_LOW_MASK | IO_PCS_PFE_ENABLE_MASK | IO_PCS_SRE_SLOW_MASK | IO_PCS_PE_PULL_DOWN_MASK)
#define CNF_IO_PCS_LOW_DS__PF__SLOW_SLEW__PULL_UP		(uint32)(IO_PCS_DSE_LOW_MASK | IO_PCS_PFE_ENABLE_MASK | IO_PCS_SRE_SLOW_MASK | IO_PCS_PE_PULL_UP_MASK)

#define CNF_IO_PCS_HIGH_DS__NO_PF__FAST_SLEW__NO_PE		(uint32)(IO_PCS_DSE_HIGH_MASK | IO_PCS_PFE_DISABLE_MASK | IO_PCS_SRE_FAST_MASK | IO_PCS_PE_DISABLED_MASK)
#define CNF_IO_PCS_HIGH_DS__NO_PF__FAST_SLEW__PULL_DOWN	(uint32)(IO_PCS_DSE_HIGH_MASK | IO_PCS_PFE_DISABLE_MASK | IO_PCS_SRE_FAST_MASK | IO_PCS_PE_PULL_DOWN_MASK)
#define CNF_IO_PCS_HIGH_DS__NO_PF__FAST_SLEW__PULL_UP	(uint32)(IO_PCS_DSE_HIGH_MASK | IO_PCS_PFE_DISABLE_MASK | IO_PCS_SRE_FAST_MASK | IO_PCS_PE_PULL_UP_MASK)
#define CNF_IO_PCS_HIGH_DS__NO_PF__SLOW_SLEW__NO_PE		(uint32)(IO_PCS_DSE_HIGH_MASK | IO_PCS_PFE_DISABLE_MASK | IO_PCS_SRE_SLOW_MASK | IO_PCS_PE_DISABLED_MASK)
#define CNF_IO_PCS_HIGH_DS__NO_PF__SLOW_SLEW__PULL_DOWN	(uint32)(IO_PCS_DSE_HIGH_MASK | IO_PCS_PFE_DISABLE_MASK | IO_PCS_SRE_SLOW_MASK | IO_PCS_PE_PULL_DOWN_MASK)
#define CNF_IO_PCS_HIGH_DS__NO_PF__SLOW_SLEW__PULL_UP	(uint32)(IO_PCS_DSE_HIGH_MASK | IO_PCS_PFE_DISABLE_MASK | IO_PCS_SRE_SLOW_MASK | IO_PCS_PE_PULL_UP_MASK)

#define CNF_IO_PCS_HIGH_DS__PF__FAST_SLEW__NO_PE		(uint32)(IO_PCS_DSE_HIGH_MASK | IO_PCS_PFE_ENABLE_MASK | IO_PCS_SRE_FAST_MASK | IO_PCS_PE_DISABLED_MASK)
#define CNF_IO_PCS_HIGH_DS__PF__FAST_SLEW__PULL_DOWN	(uint32)(IO_PCS_DSE_HIGH_MASK | IO_PCS_PFE_ENABLE_MASK | IO_PCS_SRE_FAST_MASK | IO_PCS_PE_PULL_DOWN_MASK)
#define CNF_IO_PCS_HIGH_DS__PF__FAST_SLEW__PULL_UP		(uint32)(IO_PCS_DSE_HIGH_MASK | IO_PCS_PFE_ENABLE_MASK | IO_PCS_SRE_FAST_MASK | IO_PCS_PE_PULL_UP_MASK)
#define CNF_IO_PCS_HIGH_DS__PF__SLOW_SLEW__NO_PE		(uint32)(IO_PCS_DSE_HIGH_MASK | IO_PCS_PFE_ENABLE_MASK | IO_PCS_SRE_SLOW_MASK | IO_PCS_PE_DISABLED_MASK)
#define CNF_IO_PCS_HIGH_DS__PF__SLOW_SLEW__PULL_DOWN	(uint32)(IO_PCS_DSE_HIGH_MASK | IO_PCS_PFE_ENABLE_MASK | IO_PCS_SRE_SLOW_MASK | IO_PCS_PE_PULL_DOWN_MASK)
#define CNF_IO_PCS_HIGH_DS__PF__SLOW_SLEW__PULL_UP		(uint32)(IO_PCS_DSE_HIGH_MASK | IO_PCS_PFE_ENABLE_MASK | IO_PCS_SRE_SLOW_MASK | IO_PCS_PE_PULL_UP_MASK)
/* end of DESCRIPTION */

#define CNF_IO_PCS_PORTA		(uint16)(0x0000)
#define CNF_IO_PCS_PORTB		(uint16)(0x0100)
#define CNF_IO_PCS_PORTC		(uint16)(0x0200)
#define CNF_IO_PCS_PORTD		(uint16)(0x0300)
#define CNF_IO_PCS_PORTE		(uint16)(0x0400)

/* DESCRIPTION: defines used as PortPin parameters to PCS functions */
#define CNF_IO_PCS_P0A_00 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_0)
#define CNF_IO_PCS_P0A_01 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_1)   /* UART0 Rx */
#define CNF_IO_PCS_P0A_02 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_2)   /* UART0 Tx */
#define CNF_IO_PCS_P0A_03 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_3)
#define CNF_IO_PCS_P0A_04 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_4)   /* HBR0_PWM */
#define CNF_IO_PCS_P0A_05 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_5)   /* HBR1_PWM */
#define CNF_IO_PCS_P0A_06 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_6)
#define CNF_IO_PCS_P0A_07 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_7)
#define CNF_IO_PCS_P0A_08		(CNF_IO_PCS_PORTA | IO_PCS_PIN_8)
#define CNF_IO_PCS_P0A_09 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_9)
#define CNF_IO_PCS_P0A_10 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_10)
#define CNF_IO_PCS_P0A_11 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_11)
#define CNF_IO_PCS_P0A_12 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_12)  /* STEPPER3_GPIO_OUT */
#define CNF_IO_PCS_P0A_13 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_13)  /* STEPPER4_GPIO_OUT */
#define CNF_IO_PCS_P0A_14 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_14)
#define CNF_IO_PCS_P0A_15 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_15)
#define CNF_IO_PCS_P0A_16 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_16)
#define CNF_IO_PCS_P0A_17 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_17)
#define CNF_IO_PCS_P0A_18 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_18)
#define CNF_IO_PCS_P0A_19 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_19)
#define CNF_IO_PCS_P0A_20 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_20)
#define CNF_IO_PCS_P0A_21 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_21)
#define CNF_IO_PCS_P0A_22 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_22)
#define CNF_IO_PCS_P0A_23 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_23)
#define CNF_IO_PCS_P0A_24 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_24)
#define CNF_IO_PCS_P0A_25 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_25)
#define CNF_IO_PCS_P0A_26 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_26)
#define CNF_IO_PCS_P0A_27 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_27)
#define CNF_IO_PCS_P0A_28 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_28)
#define CNF_IO_PCS_P0A_29 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_29)
#define CNF_IO_PCS_P0A_30 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_30)
#define CNF_IO_PCS_P0A_31 		(CNF_IO_PCS_PORTA | IO_PCS_PIN_31)

#define CNF_IO_PCS_P0B_00 		(CNF_IO_PCS_PORTB | IO_PCS_PIN_0)   /* ADC_IRS_FRONT */
#define CNF_IO_PCS_P0B_01 		(CNF_IO_PCS_PORTB | IO_PCS_PIN_1)   /* ADC_IRS_RIGHT */
#define CNF_IO_PCS_P0B_02 		(CNF_IO_PCS_PORTB | IO_PCS_PIN_2)   /* ADC_IRS_LEFT */
#define CNF_IO_PCS_P0B_03 		(CNF_IO_PCS_PORTB | IO_PCS_PIN_3)   /* ADC_IRS_REAR */
#define CNF_IO_PCS_P0B_04 		(CNF_IO_PCS_PORTB | IO_PCS_PIN_4)
#define CNF_IO_PCS_P0B_05 		(CNF_IO_PCS_PORTB | IO_PCS_PIN_5)
#define CNF_IO_PCS_P0B_06 		(CNF_IO_PCS_PORTB | IO_PCS_PIN_6)
#define CNF_IO_PCS_P0B_07 		(CNF_IO_PCS_PORTB | IO_PCS_PIN_7)
#define CNF_IO_PCS_P0B_08 		(CNF_IO_PCS_PORTB | IO_PCS_PIN_8)
#define CNF_IO_PCS_P0B_09 		(CNF_IO_PCS_PORTB | IO_PCS_PIN_9)
#define CNF_IO_PCS_P0B_10 		(CNF_IO_PCS_PORTB | IO_PCS_PIN_10)
#define CNF_IO_PCS_P0B_11 		(CNF_IO_PCS_PORTB | IO_PCS_PIN_11)
#define CNF_IO_PCS_P0B_12 		(CNF_IO_PCS_PORTB | IO_PCS_PIN_12)
#define CNF_IO_PCS_P0B_13 		(CNF_IO_PCS_PORTB | IO_PCS_PIN_13)
#define CNF_IO_PCS_P0B_14 		(CNF_IO_PCS_PORTB | IO_PCS_PIN_14)
#define CNF_IO_PCS_P0B_15 		(CNF_IO_PCS_PORTB | IO_PCS_PIN_15)
#define CNF_IO_PCS_P0B_16		(CNF_IO_PCS_PORTB | IO_PCS_PIN_16)
#define CNF_IO_PCS_P0B_17 		(CNF_IO_PCS_PORTB | IO_PCS_PIN_17)
#define CNF_IO_PCS_P0B_18 		(CNF_IO_PCS_PORTB | IO_PCS_PIN_18)  /* HBR0_AIN1_GPIO_OUT */
#define CNF_IO_PCS_P0B_19 		(CNF_IO_PCS_PORTB | IO_PCS_PIN_19)  /* HBR0_AIN2_GPIO_OUT */
#define CNF_IO_PCS_P0B_20		(CNF_IO_PCS_PORTB | IO_PCS_PIN_20)
#define CNF_IO_PCS_P0B_21		(CNF_IO_PCS_PORTB | IO_PCS_PIN_21)
#define CNF_IO_PCS_P0B_22		(CNF_IO_PCS_PORTB | IO_PCS_PIN_22)
#define CNF_IO_PCS_P0B_23		(CNF_IO_PCS_PORTB | IO_PCS_PIN_23)
#define CNF_IO_PCS_P0B_24		(CNF_IO_PCS_PORTB | IO_PCS_PIN_24)
#define CNF_IO_PCS_P0B_25		(CNF_IO_PCS_PORTB | IO_PCS_PIN_25)
#define CNF_IO_PCS_P0B_26		(CNF_IO_PCS_PORTB | IO_PCS_PIN_26)
#define CNF_IO_PCS_P0B_27		(CNF_IO_PCS_PORTB | IO_PCS_PIN_27)
#define CNF_IO_PCS_P0B_28		(CNF_IO_PCS_PORTB | IO_PCS_PIN_28)
#define CNF_IO_PCS_P0B_29		(CNF_IO_PCS_PORTB | IO_PCS_PIN_29)
#define CNF_IO_PCS_P0B_30		(CNF_IO_PCS_PORTB | IO_PCS_PIN_30)
#define CNF_IO_PCS_P0B_31		(CNF_IO_PCS_PORTB | IO_PCS_PIN_31)

#define CNF_IO_PCS_P0C_00 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_0)	/* HBR0_1_STBY_GPIO_OUT */
#define CNF_IO_PCS_P0C_01 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_1)
#define CNF_IO_PCS_P0C_02 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_2)
#define CNF_IO_PCS_P0C_03 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_3)	/* Pushbutton */
#define CNF_IO_PCS_P0C_04 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_4)	// PCS TEST 1
#define CNF_IO_PCS_P0C_05 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_5)   // PCS TEST 2
#define CNF_IO_PCS_P0C_06 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_6)	/* HBR1_AIN1_GPIO_OUT */
#define CNF_IO_PCS_P0C_07 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_7)	/* HBR1_AIN2_GPIO_OUT */
#define CNF_IO_PCS_P0C_08 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_8)   /* STEPPER1_GPIO_OUT */
#define CNF_IO_PCS_P0C_09 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_9)   /* STEPPER2_GPIO_OUT */
#define CNF_IO_PCS_P0C_10 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_10)
#define CNF_IO_PCS_P0C_11 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_11)
#define CNF_IO_PCS_P0C_12 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_12)
#define CNF_IO_PCS_P0C_13 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_13)
#define CNF_IO_PCS_P0C_14 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_14)
#define CNF_IO_PCS_P0C_15 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_15)
#define CNF_IO_PCS_P0C_16 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_16)
#define CNF_IO_PCS_P0C_17 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_17)
#define CNF_IO_PCS_P0C_18 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_18)
#define CNF_IO_PCS_P0C_19 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_19)
#define CNF_IO_PCS_P0C_20 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_20)
#define CNF_IO_PCS_P0C_21 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_21)
#define CNF_IO_PCS_P0C_22 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_22)
#define CNF_IO_PCS_P0C_23 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_23)
#define CNF_IO_PCS_P0C_24 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_24)
#define CNF_IO_PCS_P0C_25 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_25)
#define CNF_IO_PCS_P0C_26 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_26)
#define CNF_IO_PCS_P0C_27 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_27)
#define CNF_IO_PCS_P0C_28 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_28)
#define CNF_IO_PCS_P0C_29 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_29)
#define CNF_IO_PCS_P0C_30 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_30)
#define CNF_IO_PCS_P0C_31 		(CNF_IO_PCS_PORTC | IO_PCS_PIN_31)

#define CNF_IO_PCS_P0D_00		(CNF_IO_PCS_PORTD | IO_PCS_PIN_0)
#define CNF_IO_PCS_P0D_01 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_1)
#define CNF_IO_PCS_P0D_02 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_2)   /* UART2 Rx */
#define CNF_IO_PCS_P0D_03 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_3)   /* UART2 Tx */
#define CNF_IO_PCS_P0D_04 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_4)   /* STEPPER_EN_GPIO_OUT */
#define CNF_IO_PCS_P0D_05 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_5)   /* BLUE LED GPIO_OUT */
#define CNF_IO_PCS_P0D_06 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_6)   /* CAR_OPTO_LEFT_IN */
#define CNF_IO_PCS_P0D_07 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_7)   /* CAR_OPTO_RIGHT_IN */
#define CNF_IO_PCS_P0D_08 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_8)
#define CNF_IO_PCS_P0D_09 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_9)
#define CNF_IO_PCS_P0D_10 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_10)
#define CNF_IO_PCS_P0D_11 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_11)
#define CNF_IO_PCS_P0D_12 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_12)
#define CNF_IO_PCS_P0D_13 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_13)
#define CNF_IO_PCS_P0D_14 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_14)
#define CNF_IO_PCS_P0D_15 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_15)
#define CNF_IO_PCS_P0D_16 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_16)
#define CNF_IO_PCS_P0D_17 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_17)
#define CNF_IO_PCS_P0D_18 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_18)
#define CNF_IO_PCS_P0D_19 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_19)
#define CNF_IO_PCS_P0D_20 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_20)
#define CNF_IO_PCS_P0D_21 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_21)
#define CNF_IO_PCS_P0D_22 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_22)
#define CNF_IO_PCS_P0D_23 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_23)
#define CNF_IO_PCS_P0D_24 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_24)
#define CNF_IO_PCS_P0D_25 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_25)
#define CNF_IO_PCS_P0D_26 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_26)
#define CNF_IO_PCS_P0D_27 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_27)
#define CNF_IO_PCS_P0D_28 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_28)
#define CNF_IO_PCS_P0D_29 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_29)
#define CNF_IO_PCS_P0D_30 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_30)
#define CNF_IO_PCS_P0D_31 		(CNF_IO_PCS_PORTD | IO_PCS_PIN_31)

#define CNF_IO_PCS_P0E_00 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_0)   /* UART1 Tx */
#define CNF_IO_PCS_P0E_01 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_1)   /* UART1 Rx */
#define CNF_IO_PCS_P0E_02 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_2)
#define CNF_IO_PCS_P0E_03 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_3)
#define CNF_IO_PCS_P0E_04 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_4)
#define CNF_IO_PCS_P0E_05 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_5)
#define CNF_IO_PCS_P0E_06 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_6)
#define CNF_IO_PCS_P0E_07 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_7)
#define CNF_IO_PCS_P0E_08		(CNF_IO_PCS_PORTE | IO_PCS_PIN_8)
#define CNF_IO_PCS_P0E_09 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_9)
#define CNF_IO_PCS_P0E_10 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_10)
#define CNF_IO_PCS_P0E_11 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_11)
#define CNF_IO_PCS_P0E_12 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_12)
#define CNF_IO_PCS_P0E_13 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_13)
#define CNF_IO_PCS_P0E_14 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_14)
#define CNF_IO_PCS_P0E_15 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_15)
#define CNF_IO_PCS_P0E_16 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_16)
#define CNF_IO_PCS_P0E_17 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_17)
#define CNF_IO_PCS_P0E_18 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_18)
#define CNF_IO_PCS_P0E_19 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_19)
#define CNF_IO_PCS_P0E_20		(CNF_IO_PCS_PORTE | IO_PCS_PIN_20)   // PCS TEST
#define CNF_IO_PCS_P0E_21 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_21)   /* OPTO_GPIO_IN */
#define CNF_IO_PCS_P0E_22 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_22)   /* Adapt. H. ADC (A.L. Sensor) */
#define CNF_IO_PCS_P0E_23 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_23)   /* Adapt. H. PWM (LED control) */
#define CNF_IO_PCS_P0E_24 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_24)
#define CNF_IO_PCS_P0E_25 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_25)
#define CNF_IO_PCS_P0E_26 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_26)
#define CNF_IO_PCS_P0E_27 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_27)
#define CNF_IO_PCS_P0E_28 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_28)
#define CNF_IO_PCS_P0E_29 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_29)   /* RED LED GPIO_OUT */
#define CNF_IO_PCS_P0E_30 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_30)
#define CNF_IO_PCS_P0E_31 		(CNF_IO_PCS_PORTE | IO_PCS_PIN_31)   /* GREEN LED GPIO_OUT */
/* end of DESCRIPTION */

#define PCS_TEST_INPUT_PIN1		CNF_IO_PCS_P0C_04
#define PCS_TEST_INPUT_PIN2		CNF_IO_PCS_P0C_05
#define PCS_TEST_INPUT_PIN3		CNF_IO_PCS_P0E_20
#define PCS_TEST_INPUT_PIN4		CNF_IO_PCS_P0E_30

#define SET_LED_GREEN			CNF_IO_PCS_P0E_31
#define SET_LED_RED				CNF_IO_PCS_P0E_29
#define SET_LED_BLUE			CNF_IO_PCS_P0D_05

#define LED_GREEN 				CNF_IO_PCS_P0E_31
#define LED_RED         		CNF_IO_PCS_P0E_29
#define LED_BLUE 				CNF_IO_PCS_P0D_05

#define LED_OFF					IO_PCS_LEVEL_HIGH
#define LED_ON					IO_PCS_LEVEL_LOW

/** end of Defines **/


/** External Configuration structures **/

extern const Io_Pcs_PortTypeStruct Io_Pcs_PortCnf[];
extern const Io_Pcs_CnfTypeStruct Io_Pcs_Cnf[];

/** end of External Configuration structures **/


#endif /* IO_PCS_CNF_H */
