/****************************************************************************

COPYRIGHT (C) $Date: Sept 24, 2015 $
$CompanyInfo:  $
ALL RIGHTS RESERVED.

The reproduction, transmission or use of this document or its contents is
not permitted without express written authority.
Offenders will be liable for damages. All rights, including rights created
by patent grant or registration of a utility model or design, are reserved.
---------------------------------------------------------------------------

$ProjectName: FRDM KL26-Z PLATFORM $

$Log: io_pcs_cnf.c $

$Author: Flueran Gabriel $

 ****************************************************************************/

/** Includes **/

#include "io_pcs_cnf.h"

/** end of Includes **/

/** External Configuration structures **/

const Io_Pcs_PortTypeStruct Io_Pcs_PortCnf[] =
{
/*
 Port,    		Pin,  Pin muxing,         Initial level,	Pin direction,	Interrupt type,			Configuration */

{IO_PCS_PORTA,	1,    IO_PCS_MUX_ALT2,	  IO_PCS_INIT_LOW,  IO_PCS_INPUT,	IO_PCS_IRQC_DISABLED,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* UART0 Rx */
{IO_PCS_PORTA,  2,    IO_PCS_MUX_ALT2,	  IO_PCS_INIT_LOW,  IO_PCS_OUTPUT,  IO_PCS_IRQC_DISABLED,   CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* UART0 Tx */
{IO_PCS_PORTA,  4,    IO_PCS_MUX_ALT3,    IO_PCS_INIT_LOW,	IO_PCS_OUTPUT,	IO_PCS_IRQC_DISABLED,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* HBR0_PWM */
{IO_PCS_PORTA,  5,    IO_PCS_MUX_ALT3,    IO_PCS_INIT_LOW,	IO_PCS_OUTPUT,	IO_PCS_IRQC_DISABLED,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* HBR1_PWM */
{IO_PCS_PORTA,  12,   IO_PCS_MUX_GPIO,    IO_PCS_INIT_LOW,	IO_PCS_OUTPUT,	IO_PCS_IRQC_DISABLED,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* STEPPER3_GPIO_OUT */
{IO_PCS_PORTA,  13,   IO_PCS_MUX_GPIO,    IO_PCS_INIT_LOW,	IO_PCS_OUTPUT,	IO_PCS_IRQC_DISABLED,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* STEPPER4_GPIO_OUT */

{IO_PCS_PORTB,  0,    IO_PCS_MUX_DISABLE, IO_PCS_INIT_LOW,	IO_PCS_INPUT,	IO_PCS_IRQC_DISABLED,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* ADC_IRS_FRONT */
{IO_PCS_PORTB,  1,    IO_PCS_MUX_DISABLE, IO_PCS_INIT_LOW,	IO_PCS_INPUT,	IO_PCS_IRQC_DISABLED,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* ADC_IRS_RIGHT */
{IO_PCS_PORTB,  2,    IO_PCS_MUX_DISABLE, IO_PCS_INIT_LOW,	IO_PCS_INPUT,	IO_PCS_IRQC_DISABLED,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* ADC_IRS_LEFT */
{IO_PCS_PORTB,  3,    IO_PCS_MUX_DISABLE, IO_PCS_INIT_LOW,	IO_PCS_INPUT,	IO_PCS_IRQC_DISABLED,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* ADC_IRS_REAR */
{IO_PCS_PORTB,  18,   IO_PCS_MUX_GPIO,    IO_PCS_INIT_LOW,	IO_PCS_OUTPUT,	IO_PCS_IRQC_DISABLED,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* HBR0_AIN1_GPIO_OUT */
{IO_PCS_PORTB,  19,   IO_PCS_MUX_GPIO,    IO_PCS_INIT_LOW,	IO_PCS_OUTPUT,	IO_PCS_IRQC_DISABLED,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* HBR0_AIN2_GPIO_OUT */

{IO_PCS_PORTC,  0,    IO_PCS_MUX_GPIO,    IO_PCS_INIT_LOW,	IO_PCS_OUTPUT,	IO_PCS_IRQC_DISABLED,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* HBR0_1_STBY_GPIO_OUT */
{IO_PCS_PORTC,  6,    IO_PCS_MUX_GPIO,    IO_PCS_INIT_LOW,	IO_PCS_OUTPUT,	IO_PCS_IRQC_DISABLED,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* HBR1_AIN1_GPIO_OUT */
{IO_PCS_PORTC,  7,    IO_PCS_MUX_GPIO,    IO_PCS_INIT_LOW,	IO_PCS_OUTPUT,	IO_PCS_IRQC_DISABLED,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* HBR1_AIN2_GPIO_OUT */
{IO_PCS_PORTC,  8,    IO_PCS_MUX_GPIO,    IO_PCS_INIT_LOW,	IO_PCS_OUTPUT,	IO_PCS_IRQC_DISABLED,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* STEPPER1_GPIO_OUT */
{IO_PCS_PORTC,  9,    IO_PCS_MUX_GPIO,    IO_PCS_INIT_LOW,	IO_PCS_OUTPUT,	IO_PCS_IRQC_DISABLED,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* STEPPER2_GPIO_OUT */

{IO_PCS_PORTD,  2,    IO_PCS_MUX_ALT3,	  IO_PCS_INIT_LOW,  IO_PCS_INPUT,   IO_PCS_IRQC_DISABLED,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* UART2 Rx */
{IO_PCS_PORTD,  3,    IO_PCS_MUX_ALT3,	  IO_PCS_INIT_LOW,  IO_PCS_OUTPUT,  IO_PCS_IRQC_DISABLED,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* UART2 Tx */
{IO_PCS_PORTD,  4,    IO_PCS_MUX_GPIO,    IO_PCS_INIT_LOW,	IO_PCS_OUTPUT,	IO_PCS_IRQC_DISABLED,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* STEPPER_EN_GPIO_OUT */
{IO_PCS_PORTD,  5,    IO_PCS_MUX_GPIO,    IO_PCS_INIT_LOW,	IO_PCS_OUTPUT,	IO_PCS_IRQC_DISABLED,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* BLUE LED GPIO_OUT */
{IO_PCS_PORTD,  6,    IO_PCS_MUX_GPIO,    IO_PCS_INIT_LOW,	IO_PCS_INPUT,	IO_PCS_IRQC_INT_BOTH_EDGES,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* CAR_OPTO_LEFT_IN */
{IO_PCS_PORTD,  7,    IO_PCS_MUX_GPIO,    IO_PCS_INIT_LOW,	IO_PCS_INPUT,	IO_PCS_IRQC_INT_BOTH_EDGES,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* CAR_OPTO_RIGHT_IN */

{IO_PCS_PORTE,  0,    IO_PCS_MUX_ALT3,    IO_PCS_INIT_LOW,	IO_PCS_OUTPUT,	IO_PCS_IRQC_DISABLED,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* UART1 Tx */
{IO_PCS_PORTE,  1,    IO_PCS_MUX_ALT3,    IO_PCS_INIT_LOW,	IO_PCS_INPUT,	IO_PCS_IRQC_DISABLED,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* UART1 Rx */
{IO_PCS_PORTE,  20,   IO_PCS_MUX_GPIO,    IO_PCS_INIT_LOW,  IO_PCS_OUTPUT,  IO_PCS_IRQC_DISABLED,   CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, // PCS TEST
{IO_PCS_PORTE,	21,	  IO_PCS_MUX_GPIO,    IO_PCS_INIT_LOW,	IO_PCS_INPUT, 	IO_PCS_IRQC_DISABLED,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* OPTO_GPIO_IN */
{IO_PCS_PORTE,	22,	  IO_PCS_MUX_DISABLE, IO_PCS_INIT_LOW,	IO_PCS_INPUT,	IO_PCS_IRQC_DISABLED,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* Adapt. H. ADC (A.L. Sensor) */
{IO_PCS_PORTE,  23,   IO_PCS_MUX_ALT3,    IO_PCS_INIT_LOW,	IO_PCS_OUTPUT,	IO_PCS_IRQC_DISABLED,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* Adapt. H. PWM (LED control) */
{IO_PCS_PORTE,	29,	  IO_PCS_MUX_GPIO,    IO_PCS_INIT_LOW,	IO_PCS_OUTPUT,	IO_PCS_IRQC_DISABLED,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* RED LED GPIO_OUT */
{IO_PCS_PORTE,	31,	  IO_PCS_MUX_GPIO,    IO_PCS_INIT_LOW,	IO_PCS_OUTPUT,	IO_PCS_IRQC_DISABLED,	CNF_IO_PCS_LOW_DS__NO_PF__FAST_SLEW__NO_PE}, /* GREEN LED GPIO_OUT */

};

const Io_Pcs_CnfTypeStruct Io_Pcs_Cnf[]=
{
		{
				sizeof(Io_Pcs_PortCnf)/sizeof(Io_Pcs_PortTypeStruct),
				(const Io_Pcs_PortTypeStruct*)Io_Pcs_PortCnf
		}
};

/** end of External Configuration structures **/
